### ISSUE TITLE
Navigation integration

### ISSUE THREAD

**Issue by Dobb1000** [cocodmdr/turtlebot3_robot_localization_ws#2]
Hey 👋,
First off, amazing work on this project!

I was wondering if you've explored integrating Nav2 with it? I'm currently trying to implement it myself but am encountering some errors along the way.

Would you happen to have any suggestions or solutions for this?

Looking forward to your insights.
Best regards,

**Comment by cocodmdr** [comment]
Hey,

Thank you for your interest ! I have unfortunately not gone further with this project, so I haven't tried Nav2 integration.
You could make a pull request with Nav2 integration so that we can keep this repo up to date.

What sort of problem are you facing ?

Best regards,

**Comment by Dobb1000** [comment]
Hi there,

My setup is a bit weird, so I’ll just continue here if that’s alright with you.

My nav2 params file:

```
# Removed the 'amcl' and related parameters for GPS-based localization.

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      max_vel_x: 0.26
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      transform_tolerance: 0.2

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.22
      plugins: ["voxel_layer", "inflation_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"  # Added the required plugin parameter
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55



global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: True
      width: 50
      height: 50
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"  # Added the required plugin parameter
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55


map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "turtlebot3_world.yaml"

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: False

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "back_up", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    back_up:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: True
```

The error message after setting the goal via Rviz:
```
ros2 launch nav2_bringup navigation_launch.py use_sim_time:=true params_file:='/home/adam/turtlebot3_robot_localization_ws/src/turtlebot3/turtlebot3_navigation2/param/nav2_params.yaml'
[INFO] [launch]: All log files can be found below /home/adam/.ros/log/2025-01-03-23-25-43-073921-adam-160868
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [controller_server-1]: process started with pid [160872]
[INFO] [planner_server-2]: process started with pid [160874]
[INFO] [recoveries_server-3]: process started with pid [160876]
[INFO] [bt_navigator-4]: process started with pid [160878]
[INFO] [waypoint_follower-5]: process started with pid [160880]
[INFO] [lifecycle_manager-6]: process started with pid [160882]
[planner_server-2] [INFO] [1735943143.475271048] [planner_server]: 
[planner_server-2] 	planner_server lifecycle node launched. 
[planner_server-2] 	Waiting on external lifecycle transitions to activate
[planner_server-2] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-2] [INFO] [1735943143.491426665] [planner_server]: Creating
[waypoint_follower-5] [INFO] [1735943143.529148647] [waypoint_follower]: 
[waypoint_follower-5] 	waypoint_follower lifecycle node launched. 
[waypoint_follower-5] 	Waiting on external lifecycle transitions to activate
[waypoint_follower-5] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-5] [INFO] [1735943143.529795240] [waypoint_follower]: Creating
[bt_navigator-4] [INFO] [1735943143.559665312] [bt_navigator]: 
[bt_navigator-4] 	bt_navigator lifecycle node launched. 
[bt_navigator-4] 	Waiting on external lifecycle transitions to activate
[bt_navigator-4] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-4] [INFO] [1735943143.560739745] [bt_navigator]: Creating
[lifecycle_manager-6] [INFO] [1735943143.573501770] [lifecycle_manager_navigation]: Creating
[controller_server-1] [INFO] [1735943143.664052627] [controller_server]: 
[controller_server-1] 	controller_server lifecycle node launched. 
[controller_server-1] 	Waiting on external lifecycle transitions to activate
[controller_server-1] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-1] [INFO] [1735943143.687376310] [controller_server]: Creating controller server
[recoveries_server-3] [INFO] [1735943143.720577724] [recoveries_server]: 
[recoveries_server-3] 	recoveries_server lifecycle node launched. 
[recoveries_server-3] 	Waiting on external lifecycle transitions to activate
[recoveries_server-3] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[lifecycle_manager-6] [INFO] [1735943143.728389466] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[planner_server-2] [INFO] [1735943143.755220243] [global_costmap.global_costmap]: 
[planner_server-2] 	global_costmap lifecycle node launched. 
[planner_server-2] 	Waiting on external lifecycle transitions to activate
[planner_server-2] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-2] [INFO] [1735943143.755943921] [global_costmap.global_costmap]: Creating Costmap
[lifecycle_manager-6] [INFO] [1735943143.779708360] [lifecycle_manager_navigation]: Starting managed nodes bringup...
[lifecycle_manager-6] [INFO] [1735943143.780405079] [lifecycle_manager_navigation]: Configuring controller_server
[controller_server-1] [INFO] [1735943143.850187292] [local_costmap.local_costmap]: 
[controller_server-1] 	local_costmap lifecycle node launched. 
[controller_server-1] 	Waiting on external lifecycle transitions to activate
[controller_server-1] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-1] [INFO] [1735943143.850701925] [local_costmap.local_costmap]: Creating Costmap
[controller_server-1] [INFO] [1735943143.881265924] [controller_server]: Configuring controller interface
[controller_server-1] [INFO] [1735943143.882783239] [controller_server]: Controller frequency set to 20.0000Hz
[controller_server-1] [INFO] [1735943143.883310580] [local_costmap.local_costmap]: Configuring
[controller_server-1] [INFO] [1735943143.908790420] [local_costmap.local_costmap]: Using plugin "voxel_layer"
[controller_server-1] [INFO] [1735943143.922126037] [local_costmap.local_costmap]: Subscribed to Topics: scan
[controller_server-1] [INFO] [1735943143.945311259] [local_costmap.local_costmap]: Initialized plugin "voxel_layer"
[controller_server-1] [INFO] [1735943143.945920643] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[controller_server-1] [INFO] [1735943143.949450071] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"
[controller_server-1] [INFO] [1735943143.969881294] [controller_server]: Created progress_checker : progress_checker of type nav2_controller::SimpleProgressChecker
[controller_server-1] [INFO] [1735943143.971038520] [controller_server]: Created goal_checker : goal_checker of type nav2_controller::SimpleGoalChecker
[controller_server-1] [INFO] [1735943143.978951763] [controller_server]: Created controller : FollowPath of type dwb_core::DWBLocalPlanner
[controller_server-1] [INFO] [1735943143.981516677] [controller_server]: Setting transform_tolerance to 0.200000
[controller_server-1] [INFO] [1735943144.023444430] [controller_server]: DWBLocalPlanner
[controller_server-1] [INFO] [1735943144.033008282] [controller_server]: Using critic "RotateToGoal" (dwb_critics::RotateToGoalCritic)
[controller_server-1] [INFO] [1735943144.035408193] [controller_server]: Critic plugin initialized
[controller_server-1] [INFO] [1735943144.036005660] [controller_server]: Using critic "Oscillation" (dwb_critics::OscillationCritic)
[controller_server-1] [INFO] [1735943144.037248304] [controller_server]: Critic plugin initialized
[controller_server-1] [INFO] [1735943144.037680352] [controller_server]: Using critic "ObstacleFootprint" (dwb_critics::ObstacleFootprintCritic)
[controller_server-1] [INFO] [1735943144.040113805] [controller_server]: Critic plugin initialized
[controller_server-1] [INFO] [1735943144.041058278] [controller_server]: Using critic "GoalAlign" (dwb_critics::GoalAlignCritic)
[controller_server-1] [INFO] [1735943144.044304951] [controller_server]: Critic plugin initialized
[controller_server-1] [INFO] [1735943144.045468344] [controller_server]: Using critic "PathAlign" (dwb_critics::PathAlignCritic)
[controller_server-1] [INFO] [1735943144.046394191] [controller_server]: Critic plugin initialized
[controller_server-1] [INFO] [1735943144.047151577] [controller_server]: Using critic "PathDist" (dwb_critics::PathDistCritic)
[controller_server-1] [INFO] [1735943144.047849296] [controller_server]: Critic plugin initialized
[controller_server-1] [INFO] [1735943144.048488764] [controller_server]: Using critic "GoalDist" (dwb_critics::GoalDistCritic)
[controller_server-1] [INFO] [1735943144.049112607] [controller_server]: Critic plugin initialized
[controller_server-1] [INFO] [1735943144.049277317] [controller_server]: Controller Server has FollowPath  controllers available.
[lifecycle_manager-6] [INFO] [1735943144.065520603] [lifecycle_manager_navigation]: Configuring planner_server
[planner_server-2] [INFO] [1735943144.066066611] [planner_server]: Configuring
[planner_server-2] [INFO] [1735943144.066089736] [global_costmap.global_costmap]: Configuring
[planner_server-2] [INFO] [1735943144.084437136] [global_costmap.global_costmap]: Using plugin "obstacle_layer"
[planner_server-2] [INFO] [1735943144.092401047] [global_costmap.global_costmap]: Subscribed to Topics: scan
[planner_server-2] [INFO] [1735943144.099358026] [global_costmap.global_costmap]: Initialized plugin "obstacle_layer"
[planner_server-2] [INFO] [1735943144.099937785] [global_costmap.global_costmap]: Using plugin "inflation_layer"
[planner_server-2] [INFO] [1735943144.107813778] [global_costmap.global_costmap]: Initialized plugin "inflation_layer"
[planner_server-2] [INFO] [1735943144.136709336] [planner_server]: Created global planner plugin GridBased of type nav2_navfn_planner/NavfnPlanner
[planner_server-2] [INFO] [1735943144.137768019] [planner_server]: Configuring plugin GridBased of type NavfnPlanner
[planner_server-2] [INFO] [1735943144.172776293] [planner_server]: Planner Server has GridBased  planners available.
[lifecycle_manager-6] [INFO] [1735943144.184867808] [lifecycle_manager_navigation]: Configuring recoveries_server
[recoveries_server-3] [INFO] [1735943144.185337607] [recoveries_server]: Configuring
[recoveries_server-3] [INFO] [1735943144.210109103] [recoveries_server]: Creating recovery plugin spin of type nav2_recoveries/Spin
[recoveries_server-3] [INFO] [1735943144.211916880] [recoveries_server]: Configuring spin
[recoveries_server-3] [INFO] [1735943144.239678963] [recoveries_server]: Creating recovery plugin back_up of type nav2_recoveries/BackUp
[recoveries_server-3] [INFO] [1735943144.241071609] [recoveries_server]: Configuring back_up
[recoveries_server-3] [INFO] [1735943144.259825348] [recoveries_server]: Creating recovery plugin wait of type nav2_recoveries/Wait
[recoveries_server-3] [INFO] [1735943144.261622583] [recoveries_server]: Configuring wait
[lifecycle_manager-6] [INFO] [1735943144.279718855] [lifecycle_manager_navigation]: Configuring bt_navigator
[bt_navigator-4] [INFO] [1735943144.279955233] [bt_navigator]: Configuring
[lifecycle_manager-6] [INFO] [1735943144.364237913] [lifecycle_manager_navigation]: Configuring waypoint_follower
[waypoint_follower-5] [INFO] [1735943144.364439958] [waypoint_follower]: Configuring
[lifecycle_manager-6] [INFO] [1735943144.423335340] [lifecycle_manager_navigation]: Activating controller_server
[controller_server-1] [INFO] [1735943144.423468926] [controller_server]: Activating
[controller_server-1] [INFO] [1735943144.423499218] [local_costmap.local_costmap]: Activating
[controller_server-1] [INFO] [1735943144.423508926] [local_costmap.local_costmap]: Checking transform
[controller_server-1] [INFO] [1735943144.423598719] [local_costmap.local_costmap]: start
[lifecycle_manager-6] [INFO] [1735943144.474649526] [lifecycle_manager_navigation]: Activating planner_server
[planner_server-2] [INFO] [1735943144.475139242] [planner_server]: Activating
[planner_server-2] [INFO] [1735943144.475165201] [global_costmap.global_costmap]: Activating
[planner_server-2] [INFO] [1735943144.475173951] [global_costmap.global_costmap]: Checking transform
[planner_server-2] [INFO] [1735943144.475324620] [global_costmap.global_costmap]: start
[planner_server-2] [INFO] [1735943144.525903336] [planner_server]: Activating plugin GridBased of type NavfnPlanner
[lifecycle_manager-6] [INFO] [1735943144.526910726] [lifecycle_manager_navigation]: Activating recoveries_server
[recoveries_server-3] [INFO] [1735943144.527199647] [recoveries_server]: Activating
[recoveries_server-3] [INFO] [1735943144.527221148] [recoveries_server]: Activating spin
[recoveries_server-3] [INFO] [1735943144.527226606] [recoveries_server]: Activating back_up
[recoveries_server-3] [INFO] [1735943144.527251606] [recoveries_server]: Activating wait
[lifecycle_manager-6] [INFO] [1735943144.527730947] [lifecycle_manager_navigation]: Activating bt_navigator
[bt_navigator-4] [INFO] [1735943144.527985701] [bt_navigator]: Activating
[lifecycle_manager-6] [INFO] [1735943144.528266372] [lifecycle_manager_navigation]: Activating waypoint_follower
[waypoint_follower-5] [INFO] [1735943144.528390748] [waypoint_follower]: Activating
[lifecycle_manager-6] [INFO] [1735943144.528579501] [lifecycle_manager_navigation]: Managed nodes are active
[bt_navigator-4] [INFO] [1735943158.277820200] [bt_navigator]: Begin navigating from current location to (0.45, 1.55)
[bt_navigator-4] [ERROR] [1735943158.279051344] [bt_navigator]: Action server failed while executing action callback: "One of the children of a DecoratorNode or ControlNode is nullptr"
[bt_navigator-4] [WARN] [1735943158.279078761] [bt_navigator]: [navigate_to_pose] [ActionServer] Aborting handle.
```

After restarting nav2 bringup with the params file:
```
[controller_server-1] [INFO] [1735943601.309021493] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943601.809148939] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943602.309198383] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943602.809224619] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943603.309182853] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943603.809147253] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943604.309118238] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943604.809167265] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943605.309151958] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943605.809151860] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943606.309101093] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943606.809095995] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943607.309098188] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943607.809074672] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943608.309109575] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943608.809086976] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-1] [INFO] [1735943609.309114836] [local_costmap.local_costmap]: Timed out waiting for tra
```
